### PR TITLE
Add SSH port 2222 to the configs

### PR DESCRIPTION
**Pull request by youngnick**
Signed-off-by: Nick Young <nick@isovalent.com>

### CODE REVIEW

**Review by chancez — COMMENTED** [review]
And one last question on this: why use 2222 instead of the default of 22?

**Comment by youngnick** [comment]
Ah, because it's not a privileged port, so there's no chance of port conflicts.

**Comment by chancez** [comment]
I see. Does this prevent running multiple instances then? I don't have the issue of the port being static because I use this for my SSH config:
```
# lima Vms
Match exec "command -v limactl >/dev/null && limactl list -q | grep -q '%h'"
    StrictHostKeyChecking no
    UserKnownHostsFile /dev/null
    ProxyCommand limactl shell %h nc 127.0.0.1 22
```

Basically it uses `limactl shell` which just wraps SSH with the correct port/etc, and then it uses `nc` to forward to SSH. I believe for your setup you already needed a custom SSH config, so perhaps we can try and leverage my config to avoid needing to hardcode the port.

What do you think?

**Comment by youngnick** [comment]
I'll swap things around and see if I can get that working.

**Comment by youngnick** [comment]
Yeah, okay, I got a ProxyCommand that works on Windows:

```
Host lima
  User youngnick
  StrictHostKeyChecking no
  UserKnownHostsFile /dev/null
  ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe nebula /opt/homebrew/bin/limactl shell "%h" nc 127.0.0.1 22
```
You need to specify the user, and you have to specify the full path to SSH because Windows, but this seems to work.

**Comment by youngnick** [comment]
I'll just close then, and update my howto.

**Comment by chancez** [comment]
Oh interesting, so it doesn't require the forwardAgent option? Nice!

**Comment by youngnick** [comment]
Oh, I couldn't get the agent forwarding to work, so I hacked around it by using the ssh key from the macbook inside the VM. 😃

**Pull request closed without merging**
